# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673aIP')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('department', models.CharField(max_length=80, unique=True)),
                ('env', models.CharField(max_length=80, unique=True)),
                ('manager', models.CharField(max_length=80, unique=True)),
                ('gtype', models.CharField(max_length=80, unique=True)),
                ('networksegment', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ManyToManyField(blank=True, to='passet.Group', verbose_name='\u6240\u5c5e\u7ec4'),
        ),
    ]
