# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passet', '0003_remove_pgroup_networksegment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pgroup',
            table=None,
        ),
    ]
