# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passet', '0004_auto_20161104_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u53f7'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='department',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='env',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='gtype',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='manager',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
