# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-16 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passet', '0007_pgroup_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgroup',
            name='manager',
        ),
        migrations.AddField(
            model_name='pgroup',
            name='manager',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u5458'),
        ),
    ]
